apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smirvaki-llama-serving
  namespace: llm-serving
  labels:
    app: smirvaki-llama-serving
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smirvaki-llama-serving
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
