apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smirvaki-llama-model-pvc
  namespace: llm-serving
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
