apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smirvaki-llama-model-pvc
  namespace: cse239fall2025
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
