apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm-training

resources:
  - service-training.yaml
  - statefulset-training.yaml
  - prometheus-deployment.yaml
  - grafana-deployment.yaml

configMapGenerator:
  - name: smirvaki-trainer-configs
    files:
      - deepspeed_zero2.json=deepspeed_zero2.json
  - name: training-params
    envs:
      - training.env

generatorOptions:
  disableNameSuffixHash: true
