apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smirvaki-training-data
  namespace: cse239fall2025
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smirvaki-training-outputs
  namespace: cse239fall2025
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
