apiVersion: v1
kind: Service
metadata:
  name: smirvaki-trainer
  namespace: cse239fall2025
spec:
  clusterIP: None
  selector:
    app: smirvaki-trainer
  ports:
    - name: ds-master
      port: 6100
      targetPort: 6100
    - name: metrics
      port: 8000
      targetPort: 8000
