apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm-training

resources:
  - ../serving

patches:
  - path: patch-deployment-gpu.yaml
    target:
      kind: Deployment
      name: smirvaki-llama-serving
