apiVersion: apps/v1
kind: Deployment
metadata:
  name: smirvaki-llama-serving
  namespace: llm-training
spec:
  template:
    spec:
      nodeSelector:
        nvidia.com/gpu.present: "true"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: api
          image: docker.io/esmaeilmirvakili/llama-serving-gpu:latest
          imagePullPolicy: Always
          env:
            - name: LLAMA_GPU_LAYERS
              value: "-1"
          resources:
            requests:
              nvidia.com/gpu: "1"
              cpu: "2"
              memory: 8Gi
            limits:
              nvidia.com/gpu: "1"
              cpu: "4"
              memory: 16Gi
