apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm-training

resources:
  - job-model-download.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - nginx-config.yaml
  - prometheus-deployment.yaml
  - grafana-deployment.yaml
  - prometheus-adapter-config.yaml
  - prometheus-adapter-deployment.yaml

configMapGenerator:
  - name: smirvaki-llama-model-config
    envs:
      - model.env

generatorOptions:
  disableNameSuffixHash: true
