apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm-training

resources:
  - storageclass-filestore-rwx.yaml
  - pvc-data.yaml
  - job-preprocess.yaml

configMapGenerator:
  - name: training-params
    envs:
      - dataset.env

generatorOptions:
  disableNameSuffixHash: true
