apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smirvaki-training-data
  namespace: llm-training
spec:
  storageClassName: filestore-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smirvaki-training-outputs
  namespace: llm-training
spec:
  storageClassName: filestore-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
